[package]
name = "restapi"
version = "0.1.0"
authors = ["Daniel Toebe <dtoebe@protonmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
actix-web = "0.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
actix = "0.7"
